language: java

notifications:
  email: false

branches:
  only:
  - develop
  - master

deploy:
  provider: heroku
  api_key: "23c98db7-5f64-4328-b329-3433e559dac1"
  app: dogcare-teamdiduqui
  on:
    branch:
      - develop
      - master
