language: java

notifications:
  email: false

branches:
  only:
  - develop
  - master

before_install:
  - npm install -g @angular/cli

script:
    - ./gradlew build -x test

deploy:
  provider: heroku
  api_key:
    secure: ZHMC2UQD+tPHlGjstGB+PJDWhCx/iYKaaZtMsupLXfKFLGWrGaHUgPry4+YIfpGWi58LUtQOciquhuwD1hNsQNrLOseZ9E7p8b3DliyjyI371SDW/+4TxVJuPew4UV9FcC7S4/p4mdpqsJsE3l/myuS0D064cBwvXFHNpiX9TX5QhNmIHAc0wq1SpHgJxN06lCfyxN05jo0sYYpo489Z9z8/xUGCaS+4C6rRmMVGAyytgjLTQCk6lOP2+vnVorA9zgXjQxOjI/7se6YDKHIfGmfr48TQdOhi9xrkEO/6JdkgtshfNCbESIIOJONTn2PHzvJGfjIUyLmCYvzbOccDdq6XgyX4E1OAsx7x8DGQ/SQ/JBXGk7NaO4MIY9GndYmwReOE9ResXFE1S5lsatfiev1rvSkyhprt5Vm/vdzGsl2o+6w2+zeaNhCg7u1Pst7DQr8W+tBeWQCculFhoVwrpho4W8xndAL5J1NHBwX2HG0tDwbxcewddOZ3rVcw2HghNzAlHPH+HcQgE9/uI4pI696XQ+UUq4P5anQNTL07d/H5/cu3uaJGN/JudD99fJxkCd/dGDphauZ1mm7+139Kt8Wb7myhovDC/r9rssswcXiOzW73sLtQpThCQQuSa+bgDLoBvpALcVwzDin74gjSITl8MCEnrxa+/1y/yWQ9P5E=
  app: dogcare-teamdiduqui
  skip_cleanup: true
  on:
    branch:
      - develop
      - master
